[project]
name = "hello-app"
version = "0.1.0"
description = "Basic FastAPI Hello World example"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "uvicorn>=0.40.0",
]
